### PR TITLE
Compare BEM results

### PR DESCRIPTION
**Pull request by kmruehl**
@jtgrasb I went ahead and added the [Compare_BEM](https://github.com/WEC-Sim/WEC-Sim/projects/58#card-77446108) functionality because it's an important feature to be able to directly compare these BEM results. Take a look and LMK what you think.

### CODE REVIEW

**Comment by kmruehl** [comment]
@akeeste this relates to PR [#790](https://github.com/WEC-Sim/WEC-Sim/pull/790) as well. I submitted this PR into Jeff's fork because there's an immediate need on his fork, but it may be worth merging into your PR first and including it in the updated BEMIO naming convention

**Comment by jtgrasb** [comment]
@kmruehl Thanks for putting this together! I have a few thoughts that I just wanted to confirm with you here. 
1. This workflow for the compare BEM is to load in two hydro structs and Plot_BEMIO will plot them together, correct? This makes sense to me and I like that it doesn't need to add another function. 
2. I ran into some issues with plotting the normal cases which I was able to fix pretty easily, but I don't have push access so not sure the best way to implement those changes,

**Comment by kmruehl** [comment]
@jtgrasb
1. Yes, I've just extended plotBEMIO to allow for multiple hydro inputs at a time, without combining them and writing them to a h5.
2. I actually made quite a few updates to these functions on @akeeste's PR https://github.com/WEC-Sim/WEC-Sim/pull/790. We are hoping to merge this PR into dev tomorrow. There are several ways we can get these updates into your fork, so let's chat about the best workflow to incorporate them. Once they're in your fork, further improvements are always welcome.

**Comment by kmruehl** [comment]
@jtgrasb closing this PR as we merge #790 into dev

**Pull request closed without merging**
