### PR TITLE
added plotWaves to examples and resolved slx file issues

### PR DESCRIPTION
**Pull request by kmruehl**
@jtgrasb and @akeeste I made some minor revisions in this PR, feel free to merge or resolve them elsewhere. 
- added output.plotWaves to examples, we could comment this but provide it as an example
- resolved issues with examples files to use the wecSimInputFile instead of custom parameters

To Do
- [x] add documentation

### CODE REVIEW

**Comment by jtgrasb** [comment]
@kmruehl @akeeste It seems useful to include the call to the function in userDefinedFunctions, but it does add a lot to the simulation time. Maybe we should add it commented out as an example for users to uncomment when needed?

**Comment by akeeste** [comment]
> @kmruehl @akeeste It seems useful to include the call to the function in userDefinedFunctions, but it does add a lot to the simulation time. Maybe we should add it commented out as an example for users to uncomment when needed?

I agree, let's put it in a userDefinedFunction but comment it out by default. Thanks Jeff!

**Comment by kmruehl** [comment]
Yes, I agree too. No need to merge this PR, especially if no one else is having the issue with the examples. You can just make the revisions directly to `userDefinedFunctions.m`

**Comment by kmruehl** [comment]
@jtgrasb you can disregard the slx files changes, I've run the examples from your fork now without issues. I'm going to go ahead and close this PR.

**Pull request closed without merging**
